global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'monitoring-item'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['prometheus:9090', 'node_exporter:9100']
        labels:
          service: 'monitor'
  
  - job_name: 'postgres'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['postgre_exporter:9187']
        labels:
          service: 'monitor'

  - job_name: 'minio-job'
    metrics_path: '/minio/v2/metrics/cluster'
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg3MzMzNzM0MX0.XWS6G5ohtnBG-cUBsg3aW9ooUSuH_bL0t5B4RTh0tkgpI6V4tjrx9uXclPlDSAq6f4wt6-0NsCVuejefAhnG4A
    scheme: 'http'
    static_configs:
      - targets: ['minio:9000']

  - job_name: fastapi
    honor_labels: true
    static_configs:
    - targets: ['api-web:8080']  # metrics from model
